apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: satya1027/notification-service:v1
        imagePullPolicy: Always

        ports:
        - containerPort: 8085

        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/ecommerce
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: Root@123
